// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type Entry struct {
	ID            string  `db:"id" json:"id"`
	Title         string  `db:"title" json:"title"`
	Username      []byte  `db:"username" json:"username"`
	Password      []byte  `db:"password" json:"password"`
	Url           []byte  `db:"url" json:"url"`
	Notes         []byte  `db:"notes" json:"notes"`
	TotpSecret    []byte  `db:"totp_secret" json:"totp_secret"`
	TotpIssuer    *string `db:"totp_issuer" json:"totp_issuer"`
	TotpAlgorithm string  `db:"totp_algorithm" json:"totp_algorithm"`
	TotpDigits    int64   `db:"totp_digits" json:"totp_digits"`
	TotpPeriod    int64   `db:"totp_period" json:"totp_period"`
	CreatedAt     int64   `db:"created_at" json:"created_at"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	DeletedAt     *int64  `db:"deleted_at" json:"deleted_at"`
}

type SyncState struct {
	DeviceID     string  `db:"device_id" json:"device_id"`
	ServerUrl    *string `db:"server_url" json:"server_url"`
	LastSyncedAt *int64  `db:"last_synced_at" json:"last_synced_at"`
}

type VaultMetum struct {
	ID        string `db:"id" json:"id"`
	Name      string `db:"name" json:"name"`
	Salt      []byte `db:"salt" json:"salt"`
	Verifier  []byte `db:"verifier" json:"verifier"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}
