// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_meta_gen.sql

package repo_vault

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

const create = `-- name: Create :one
INSERT INTO vault_meta (id, name, salt, verifier, created_at, updated_at)
	VALUES (?, ?, ?, ?, ?, ?)
	RETURNING id, name, salt, verifier, created_at, updated_at
`

type CreateParams struct {
	ID        string `db:"id" json:"id"`
	Name      string `db:"name" json:"name"`
	Salt      []byte `db:"salt" json:"salt"`
	Verifier  []byte `db:"verifier" json:"verifier"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Salt,
		arg.Verifier,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i models.VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Verifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM vault_meta WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, name, salt, verifier, created_at, updated_at FROM vault_meta WHERE id=? LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id string) (*models.VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i models.VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Verifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE vault_meta
	SET name=?, salt=?, verifier=?
	WHERE id=?
	RETURNING id, name, salt, verifier, created_at, updated_at
`

type UpdateParams struct {
	Name     string `db:"name" json:"name"`
	Salt     []byte `db:"salt" json:"salt"`
	Verifier []byte `db:"verifier" json:"verifier"`
	ID       string `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Name,
		arg.Salt,
		arg.Verifier,
		arg.ID,
	)
	var i models.VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Verifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
