// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_meta.sql

package repo_vault

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

const getAll = `-- name: GetAll :one
SELECT id, name, salt, verifier, created_at, updated_at FROM vault_meta
`

func (q *Queries) GetAll(ctx context.Context) (*models.VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, getAll)
	var i models.VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Verifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getByName = `-- name: GetByName :one
SELECT id, name, salt, verifier, created_at, updated_at FROM vault_meta WHERE name=? LIMIT 1
`

func (q *Queries) GetByName(ctx context.Context, name string) (*models.VaultMetum, error) {
	row := q.db.QueryRowContext(ctx, getByName, name)
	var i models.VaultMetum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Verifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
