// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package repo_entry

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

const getWithPaginate = `-- name: GetWithPaginate :many
SELECT id, title, username, password, url, notes, totp_secret, totp_issuer, totp_algorithm, totp_digits, totp_period, created_at, updated_at, deleted_at FROM entries WHERE deleted_at IS NULL ORDER BY name DESC LIMIT ? OFFSET ?
`

type GetWithPaginateParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetWithPaginate(ctx context.Context, arg GetWithPaginateParams) ([]*models.Entry, error) {
	rows, err := q.db.QueryContext(ctx, getWithPaginate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*models.Entry{}
	for rows.Next() {
		var i models.Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Username,
			&i.Password,
			&i.Url,
			&i.Notes,
			&i.TotpSecret,
			&i.TotpIssuer,
			&i.TotpAlgorithm,
			&i.TotpDigits,
			&i.TotpPeriod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
