// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries_gen.sql

package repo_entry

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

const create = `-- name: Create :exec
INSERT INTO entries (id, title, username, password, url, notes, totp_secret, totp_issuer, totp_algorithm, totp_digits, totp_period, created_at, updated_at, deleted_at)
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateParams struct {
	ID            string  `db:"id" json:"id"`
	Title         string  `db:"title" json:"title"`
	Username      []byte  `db:"username" json:"username"`
	Password      []byte  `db:"password" json:"password"`
	Url           []byte  `db:"url" json:"url"`
	Notes         []byte  `db:"notes" json:"notes"`
	TotpSecret    []byte  `db:"totp_secret" json:"totp_secret"`
	TotpIssuer    *string `db:"totp_issuer" json:"totp_issuer"`
	TotpAlgorithm string  `db:"totp_algorithm" json:"totp_algorithm"`
	TotpDigits    int64   `db:"totp_digits" json:"totp_digits"`
	TotpPeriod    int64   `db:"totp_period" json:"totp_period"`
	CreatedAt     int64   `db:"created_at" json:"created_at"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	DeletedAt     *int64  `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create,
		arg.ID,
		arg.Title,
		arg.Username,
		arg.Password,
		arg.Url,
		arg.Notes,
		arg.TotpSecret,
		arg.TotpIssuer,
		arg.TotpAlgorithm,
		arg.TotpDigits,
		arg.TotpPeriod,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM entries WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, title, username, password, url, notes, totp_secret, totp_issuer, totp_algorithm, totp_digits, totp_period, created_at, updated_at, deleted_at FROM entries WHERE id=? LIMIT 1
`

func (q *Queries) Get(ctx context.Context, id string) (*models.Entry, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Notes,
		&i.TotpSecret,
		&i.TotpIssuer,
		&i.TotpAlgorithm,
		&i.TotpDigits,
		&i.TotpPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const update = `-- name: Update :one
UPDATE entries
	SET title=?, username=?, password=?, url=?, notes=?, totp_secret=?, 
		totp_issuer=?, totp_algorithm=?, totp_digits=?, totp_period=?, deleted_at=?
	WHERE id=?
	RETURNING id, title, username, password, url, notes, totp_secret, totp_issuer, totp_algorithm, totp_digits, totp_period, created_at, updated_at, deleted_at
`

type UpdateParams struct {
	Title         string  `db:"title" json:"title"`
	Username      []byte  `db:"username" json:"username"`
	Password      []byte  `db:"password" json:"password"`
	Url           []byte  `db:"url" json:"url"`
	Notes         []byte  `db:"notes" json:"notes"`
	TotpSecret    []byte  `db:"totp_secret" json:"totp_secret"`
	TotpIssuer    *string `db:"totp_issuer" json:"totp_issuer"`
	TotpAlgorithm string  `db:"totp_algorithm" json:"totp_algorithm"`
	TotpDigits    int64   `db:"totp_digits" json:"totp_digits"`
	TotpPeriod    int64   `db:"totp_period" json:"totp_period"`
	DeletedAt     *int64  `db:"deleted_at" json:"deleted_at"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*models.Entry, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Title,
		arg.Username,
		arg.Password,
		arg.Url,
		arg.Notes,
		arg.TotpSecret,
		arg.TotpIssuer,
		arg.TotpAlgorithm,
		arg.TotpDigits,
		arg.TotpPeriod,
		arg.DeletedAt,
		arg.ID,
	)
	var i models.Entry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Username,
		&i.Password,
		&i.Url,
		&i.Notes,
		&i.TotpSecret,
		&i.TotpIssuer,
		&i.TotpAlgorithm,
		&i.TotpDigits,
		&i.TotpPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
