// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_entry

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	Delete(ctx context.Context, id string) error
	Get(ctx context.Context, id string) (*models.Entry, error)
	GetWithPaginate(ctx context.Context, arg GetWithPaginateParams) ([]*models.Entry, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Entry, error)
}

var _ Querier = (*Queries)(nil)
