// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_sync

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

type Querier interface {
	Get(ctx context.Context) (*models.SyncState, error)
	UpdateLastSyncedAt(ctx context.Context, arg UpdateLastSyncedAtParams) error
	UpdateServerURL(ctx context.Context, arg UpdateServerURLParams) error
	Upsert(ctx context.Context, arg UpsertParams) error
}

var _ Querier = (*Queries)(nil)
