// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package repo_sync

import (
	"context"

	"github.com/stickpro/kyp/internal/models"
)

const get = `-- name: Get :one
SELECT device_id, server_url, last_synced_at FROM sync_state LIMIT 1
`

func (q *Queries) Get(ctx context.Context) (*models.SyncState, error) {
	row := q.db.QueryRowContext(ctx, get)
	var i models.SyncState
	err := row.Scan(&i.DeviceID, &i.ServerUrl, &i.LastSyncedAt)
	return &i, err
}

const updateLastSyncedAt = `-- name: UpdateLastSyncedAt :exec
UPDATE sync_state SET last_synced_at = ? WHERE device_id = ?
`

type UpdateLastSyncedAtParams struct {
	LastSyncedAt *int64 `db:"last_synced_at" json:"last_synced_at"`
	DeviceID     string `db:"device_id" json:"device_id"`
}

func (q *Queries) UpdateLastSyncedAt(ctx context.Context, arg UpdateLastSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastSyncedAt, arg.LastSyncedAt, arg.DeviceID)
	return err
}

const updateServerURL = `-- name: UpdateServerURL :exec
UPDATE sync_state SET server_url = ? WHERE device_id = ?
`

type UpdateServerURLParams struct {
	ServerUrl *string `db:"server_url" json:"server_url"`
	DeviceID  string  `db:"device_id" json:"device_id"`
}

func (q *Queries) UpdateServerURL(ctx context.Context, arg UpdateServerURLParams) error {
	_, err := q.db.ExecContext(ctx, updateServerURL, arg.ServerUrl, arg.DeviceID)
	return err
}

const upsert = `-- name: Upsert :exec
INSERT INTO sync_state (device_id, server_url, last_synced_at)
    VALUES (?, ?, ?)
    ON CONFLICT (device_id) DO UPDATE SET
        server_url     = excluded.server_url,
        last_synced_at = excluded.last_synced_at
`

type UpsertParams struct {
	DeviceID     string  `db:"device_id" json:"device_id"`
	ServerUrl    *string `db:"server_url" json:"server_url"`
	LastSyncedAt *int64  `db:"last_synced_at" json:"last_synced_at"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) error {
	_, err := q.db.ExecContext(ctx, upsert, arg.DeviceID, arg.ServerUrl, arg.LastSyncedAt)
	return err
}
