// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CreateEntry(arg1:gui.EntryDTO):Promise<void>;

export function CreateVault(arg1:string,arg2:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GeneratePassword(arg1:number):Promise<string>;

export function GetEntry(arg1:string):Promise<gui.EntryDTO>;

export function GetTOTPCode(arg1:string):Promise<gui.TOTPState>;

export function HasVault():Promise<boolean>;

export function ListEntries():Promise<Array<gui.EntryDTO>>;

export function ListVaults():Promise<Array<string>>;

export function Lock():Promise<void>;

export function ReportActivity():Promise<void>;

export function Unlock(arg1:string,arg2:string):Promise<void>;

export function UpdateEntry(arg1:string,arg2:gui.EntryDTO):Promise<void>;
