// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1) {
  return window['go']['gui']['App']['CreateEntry'](arg1);
}

export function CreateVault(arg1, arg2) {
  return window['go']['gui']['App']['CreateVault'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['gui']['App']['DeleteEntry'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['gui']['App']['GeneratePassword'](arg1);
}

export function GetEntry(arg1) {
  return window['go']['gui']['App']['GetEntry'](arg1);
}

export function GetTOTPCode(arg1) {
  return window['go']['gui']['App']['GetTOTPCode'](arg1);
}

export function HasVault() {
  return window['go']['gui']['App']['HasVault']();
}

export function ListEntries() {
  return window['go']['gui']['App']['ListEntries']();
}

export function ListVaults() {
  return window['go']['gui']['App']['ListVaults']();
}

export function Lock() {
  return window['go']['gui']['App']['Lock']();
}

export function ReportActivity() {
  return window['go']['gui']['App']['ReportActivity']();
}

export function Unlock(arg1, arg2) {
  return window['go']['gui']['App']['Unlock'](arg1, arg2);
}

export function UpdateEntry(arg1, arg2) {
  return window['go']['gui']['App']['UpdateEntry'](arg1, arg2);
}
